import { AppDataState } from '../types';

export const INITIAL_APP_DATA: AppDataState = {
  projectInput: {
    clientName: 'Apex Manufacturing Ltd.',
    projectName: 'Thermal & Power Plant Upgrade',
    demandMode: 'Useful Energy (GJ)',
    annualEnergyDemand: 50000,
    annualOperatingHours: 7200,
    discountRateWACC: 0.08,
    amortizationYears: 10,
  },
  fuelAssumptions: [
    {
      id: 'fuel-ng',
      energyCarrier: 'Natural Gas',
      pricingUnit: 'm³',
      fuelUnitPrice: 0.45,
      lhvMJPerUnit: 35.5,
      thermalEfficiency: 0.85,
      heatPumpCOP: null,
      monthlyFixedCharge: 500,
    },
    {
      id: 'fuel-lpg',
      energyCarrier: 'LPG',
      pricingUnit: 'L',
      fuelUnitPrice: 0.68,
      lhvMJPerUnit: 25.5,
      thermalEfficiency: 0.82,
      heatPumpCOP: null,
      monthlyFixedCharge: 250,
    },
    {
      id: 'fuel-elec',
      energyCarrier: 'Electricity',
      pricingUnit: 'kWh',
      fuelUnitPrice: 0.12,
      lhvMJPerUnit: 3.6,
      thermalEfficiency: null,
      heatPumpCOP: 3.5,
      monthlyFixedCharge: 1200,
    },
    {
      id: 'fuel-diesel',
      energyCarrier: 'Diesel',
      pricingUnit: 'L',
      fuelUnitPrice: 1.05,
      lhvMJPerUnit: 36.0,
      thermalEfficiency: 0.8,
      heatPumpCOP: null,
      monthlyFixedCharge: 100,
    },
  ],
  infrastructureAssumptions: [
    {
      id: 'infra-ng',
      energyCarrier: 'Natural Gas',
      storagePressureCapex: 45000,
      connectionPipingCapex: 65000,
      endUseEquipmentCapex: 120000,
      annualOmRate: 0.025,
    },
    {
      id: 'infra-lpg',
      energyCarrier: 'LPG',
      storagePressureCapex: 35000,
      connectionPipingCapex: 25000,
      endUseEquipmentCapex: 110000,
      annualOmRate: 0.03,
    },
    {
      id: 'infra-elec',
      energyCarrier: 'Electricity',
      storagePressureCapex: 0,
      connectionPipingCapex: 95000,
      endUseEquipmentCapex: 280000,
      annualOmRate: 0.02,
    },
    {
      id: 'infra-diesel',
      energyCarrier: 'Diesel',
      storagePressureCapex: 25000,
      connectionPipingCapex: 15000,
      endUseEquipmentCapex: 95000,
      annualOmRate: 0.035,
    },
  ],
  assumptionRegister: [
    {
      id: 'ASM-NG-01',
      category: 'Fuel Price',
      parameterField: 'Natural Gas Unit Price',
      currentValue: '$0.45 / m³',
      dataSource: 'Piped Natural Gas Tariff Schedule Q2',
      verificationDate: '2026-06-15',
      owner: 'Energy Procurement Team',
    },
    {
      id: 'ASM-LPG-01',
      category: 'Fuel Price',
      parameterField: 'LPG Tank Bulk Price',
      currentValue: '$0.68 / L',
      dataSource: 'Commercial Fuel Supplier Quote',
      verificationDate: '2026-06-20',
      owner: 'Supply Chain Operations',
    },
    {
      id: 'ASM-ELE-01',
      category: 'Fuel Price',
      parameterField: 'Industrial Power Rate',
      currentValue: '$0.12 / kWh',
      dataSource: 'Regional Utility Grid Tariff (Band B)',
      verificationDate: '2026-07-01',
      owner: 'Facility Engineer',
    },
    {
      id: 'ASM-DSL-01',
      category: 'Fuel Price',
      parameterField: 'Low Sulfur Diesel Price',
      currentValue: '$1.05 / L',
      dataSource: 'National Petroleum Index Average',
      verificationDate: '2026-07-10',
      owner: 'Procurement Manager',
    },
    {
      id: 'ASM-EFF-01',
      category: 'Efficiency',
      parameterField: 'Gas Boiler & Heat Pump Efficiency/COP',
      currentValue: 'Boiler 85% / COP 3.50',
      dataSource: 'OEM Equipment Technical Datasheets',
      verificationDate: '2026-05-18',
      owner: 'Lead Mechanical Engineer',
    },
    {
      id: 'ASM-FIN-01',
      category: 'Finance',
      parameterField: 'WACC & Amortization Period',
      currentValue: '8.0% WACC / 10 Yrs',
      dataSource: 'Corporate Treasury Benchmark',
      verificationDate: '2026-01-10',
      owner: 'CFO Office',
    },
  ],
  lastSaved: null,
};
